controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_command_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_controller:
      type: joint_state_controller/JointStateController

velocity_controller:
  ros__parameters:
    joints:
      - left_thruster_joint
      - right_thruster_joint

forward_command_controller:
  ros__parameters:
    joints:
      - left_azimuth_joint
      - right_azimuth_joint
    interface_name: position